# Generated by Django 5.1.1 on 2024-09-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_order_time'),
        ('openId', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='openId.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
